version: "3"
services:

  rabbitmq:
    image: rabbitmq:management
    container_name: task-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      node_net:
        ipv4_address: 172.20.0.5

networks:
  node_net:
    ipam:
      config:
        - subnet: 172.20.0.0/24